name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build the application
        run: go build -o ${{ github.sha }} .

      - name: Install SSH Client
        run: sudo apt-get install -y ssh sshpass

      - name: Copy the binary to the VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: sshpass -p "$VM_PASSWORD" scp -o StrictHostKeyChecking=no ${{ github.sha }} $VM_USER@$VM_HOST:~/nuqta-service

      - name: Start new application version on alternate port
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          echo "$VM_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST '
            cd ~/nuqta-service
          
            chmod +x ${{ github.sha }}
            echo ${{ github.sha }} > new_binary_name.txt
          
            PID=$(cat pid.txt)
            if ps -p $PID > /dev/null; then
              kill -TERM $PID
              sleep 10
            fi
          
            NEW_PORT=$((1024 + RANDOM % 64512))
            for i in {1..10}; do
              if ! sudo lsof -i:$NEW_PORT; then
                break
              fi
              NEW_PORT=$((1024 + RANDOM % 64512))
            done
            echo $NEW_PORT > new_port.txt
          
            PORT=$(cat port.txt)
            sed -i "s/PORT=$PORT/PORT=$NEW_PORT/" .env
          
            nohup ./starter.sh ${{ github.sha }} &>> app.log &
            echo $! > pid.txt
          '

      - name: Switch Nginx to new version
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        run: |
          sshpass -p "$VM_PASSWORD" ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST '
            cd ~/nuqta-service
          
            PORT=$(cat port.txt)
            NEW_PORT=$(cat new_port.txt)
          
            sudo sed -i "s/127.0.0.1:$PORT/127.0.0.1:$NEW_PORT/" /etc/nginx/sites-available/nuqta-service.chuqurtech.uz
            sudo systemctl reload nginx
            mv new_port.txt port.txt
          '